security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto' # Adding hashing for User entity
    providers:
        app_user_provider: # Renaming the provider
            entity:
                class: App\Entity\User
                property: email # Authenticating users based on their email addresses
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider # Using the updated provider
            # Rest of your firewall configuration...
