#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_user_index:
  path: /user
  controller: App\Controller\UserController::index
  methods: GET

app_user_show:
  path: /user/{userid}
  controller: App\Controller\UserController::show
  methods: GET

app_user_delete:
  path: /user/{userid}/delete
  controller: App\Controller\UserController::delete
  methods: POST

app_user_new:
  path: /user/new
  controller: App\Controller\UserController::new
  methods: GET|POST

app_user_edit:
  path: /user/{userid}/edit
  controller: App\Controller\UserController::edit
  methods: GET|POST

check_login:
  path: /check_login
  controller: App\Controller\SecurityController::checkLogin
  methods: [POST]
